# path to sample sheet
samples: "config/samples.tsv"

# contrasts for the limma results method
contrasts:
  cancer_vs_normal:
    - cancer - normal

# organism genome build (only human at current - hg38, hg19)
organism: hg38

# methylation array (HM450, EPIC)
array: HM450

# chainfile (if no liftover needed - leave as default below)
chain: hg19ToHg38.over.chain

# colours for plots
fill:
  all: 
    cancer: "Red"
    normal: "Blue"
  detpqc: 
    cancer: "Red"
    normal: "Blue"
  densityqc: 
    cancer: "Red"
    normal: "Blue"
  boxplotqc:
    cancer: "Red"
    normal: "Blue"
  pca: 
    cancer: "Red"
    normal: "Blue"
  densityheatmap: 
    cancer: "Red"
    normal: "Blue"