# path to sample sheet
samples: "config/samples.tsv"

# contrasts for the limma results method
contrasts:
  cancer_vs_normal:
    - cancer - normal

# colours for plots
fill:
  detpqc: "Red,Blue"
  densityqc: "Red,Blue"
  boxplotqc: "Red,Blue"
  pca: "Red,Blue"