# path to sample sheet
samples: "config/samples.tsv"

# contrasts for the limma results method
contrasts:
  cancer_vs_normal:
    - cancer - normal

# organism genome build (only human at current - hg38, hg19)
organism: hg38

# methylation array (HM450K, EPIC)
array: HM450

# chainfile (if no liftover needed - leave as default below)
chain: hg19ToHg38.over.chain

# colours for plots
fill:
  detpqc: "Red,Blue"
  densityqc: "Red,Blue"
  boxplotqc: "Red,Blue"
  pca: "Red,Blue"
  densityheatmap: "Blue,Blue,Red,Red,Blue,Red"