$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  
  samples:
    type: string
  
  organism:
    type: string
  
  array:
    type: string
  
  contrasts:
    type: object

  fill:
    type: object

required:
  - samples
  - organism
  - array
  - contrasts
  - fill