$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  
  samples:
    type: string
  
  # organism:
  #   type: string
  
  # platform:
  #   type: string
  
  # annotation:
  #   type: string
  
  contrasts:
    type: object

  fill:
    type: object

required:
  - samples
  # - organism
  # - platform
  # - annotation
  - contrasts
  - fill