channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-minfi
  - r-ggplot2
  - r-reshape2
  - libopenblas=0.3.3
  - bioconductor-illuminahumanmethylation450kmanifest
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
  - bioconductor-sesamedata

# sesameData
# minfi
# RColorBrewer
# org.Hs.eg.db
# DNAcopy
# conumee
# minfiData
# sva
# IlluminaHumanMethylationEPICanno.ilm10b4.hg19
# shinyMethyl
# ggplot2
# IlluminaMethylationManifest
# IlluminaHumanMethylationEPICmanifest
