channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-minfi
  - r-ggplot2
  - r-reshape2
  - r-ggrepel
  - libopenblas=0.3.3
  - bioconductor-illuminahumanmethylation450kmanifest
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
  - bioconductor-complexheatmap
  - bioconductor-dmrcate
  - bioconductor-dmrcatedata
  - bioconductor-experimenthub
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-genomicranges
  - bioconductor-chippeakanno
  - bioconductor-org.hs.eg.db

# bioconductor-sesamedata - NOTE does not seem to work for some reason - instead am downloading rds as static files and have kept in resources folder
# minfi
# RColorBrewer
# org.Hs.eg.db
# DNAcopy
# conumee
# minfiData
# sva
# IlluminaHumanMethylationEPICanno.ilm10b4.hg19
# shinyMethyl
# ggplot2
# IlluminaMethylationManifest
# IlluminaHumanMethylationEPICmanifest
